<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-01 at 19:28:56.
 */
require_once '../includes/post_class.php';
class post_classTest extends PHPUnit_Framework_TestCase {

    /**
     * @var post_class
     */
    private $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new post_class(1,"Hello","hello","default.png","2017-04-30 16:13:51",12,"test,test",1,"",1);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        unset($this->object);
    }

    /**
     * @covers post_class::getPost_id
     * @todo   Implement testGetPost_id().
     */
    public function testGetPost_id() {
        $this->assertEquals(1, $this->object->getPost_id());
    }

    /**
     * @covers post_class::getPost_title
     * @todo   Implement testGetPost_title().
     */
    public function testGetPost_title() {
        $this->assertEquals("Hello", $this->object->getPost_title());
    }

    /**
     * @covers post_class::getPost_content
     * @todo   Implement testGetPost_content().
     */
    public function testGetPost_content() {
        $this->assertEquals("hello", $this->object->getPost_content());
    }

    /**
     * @covers post_class::getPost_image
     * @todo   Implement testGetPost_image().
     */
    
    public function testGetPost_image() {
        $this->assertEquals("default.png",$this->object->getPost_image());
    }

    /**
     * @covers post_class::getPost_date
     * @todo   Implement testGetPost_date().
     */
    
    public function testGetPost_date() {
        $this->assertEquals("2017-04-30 16:13:51",$this->object->getPost_date());
    }

    /**
     * @covers post_class::getPost_like
     * @todo   Implement testGetPost_like().
     */
    public function testGetPost_like() {
        $this->assertEquals(12,$this->object->getPost_like());
    }

    /**
     * @covers post_class::getPost_tags
     * @todo   Implement testGetPost_tags().
     */
    public function testGetPost_tags() {
        $this->assertEquals("test,test",$this->object->getPost_tags());
    }

    /**
     * @covers post_class::getAllow_comments
     * @todo   Implement testGetAllow_comments().
     */ 
    public function testGetAllow_comments() {
        $this->assertEquals(1,$this->object->getAllow_comments());
    }

    /**
     * @covers post_class::getPost_likers
     * @todo   Implement testGetPost_likers().
     */
    public function testGetPost_likers() {
        $this->assertEquals("",$this->object->getPost_likers());
    }

    /**
     * @covers post_class::getMember_id
     * @todo   Implement testGetMember_id().
     */
    public function testGetMember_id() {
       $this->assertEquals(1,$this->object->getMember_id());
    }

    /**
     * @covers post_class::setPost_id
     * @todo   Implement testSetPost_id().
     */
    public function testSetPost_id() {
        $this->object->setPost_id(1);
        $this->assertEquals(1, $this->object->getPost_id());
    }

    /**
     * @covers post_class::setPost_title
     * @todo   Implement testSetPost_title().
     */
    public function testSetPost_title() {
        $this->object->setPost_title("Hello");
        $this->assertEquals("Hello", $this->object->getPost_title());
    }

    /**
     * @covers post_class::setPost_content
     * @todo   Implement testSetPost_content().
     */
    public function testSetPost_content() {
        $this->object->setPost_content("hello");
        $this->assertEquals("hello", $this->object->getPost_content());
    }

    /**
     * @covers post_class::setPost_image
     * @todo   Implement testSetPost_image().
     */
    public function testSetPost_image() {
        $this->object->setPost_image("default.png");
        $this->assertEquals("default.png",$this->object->getPost_image());
    }

    /**
     * @covers post_class::setPost_date
     * @todo   Implement testSetPost_date().
     */
    public function testSetPost_date() {
        $this->object->setPost_date("2017-04-30 16:13:51");
        $this->assertEquals("2017-04-30 16:13:51",$this->object->getPost_date());
    }

    /**
     * @covers post_class::setPost_like
     * @todo   Implement testSetPost_like().
     */
    public function testSetPost_like() {
        $this->object->setPost_like(12);
        $this->assertEquals(12,$this->object->getPost_like());
    }

    /**
     * @covers post_class::setPost_tags
     * @todo   Implement testSetPost_tags().
     */
    public function testSetPost_tags() {
        $this->object->setPost_tags("test,test");
        $this->assertEquals("test,test",$this->object->getPost_tags());
    }

    /**
     * @covers post_class::setAllow_comments
     * @todo   Implement testSetAllow_comments().
     */
    public function testSetAllow_comments() {
        $this->object->setAllow_comments(1);
        $this->assertEquals(1,$this->object->getAllow_comments());
    }

    /**
     * @covers post_class::setPost_likers
     * @todo   Implement testSetPost_likers().
     */
    public function testSetPost_likers() {
        $this->object->setPost_likers("");
        $this->assertEquals("",$this->object->getPost_likers());
    }

    /**
     * @covers post_class::setMember_id
     * @todo   Implement testSetMember_id().
     */
    public function testSetMember_id() {
        $this->object->setMember_id(1);
        $this->assertEquals(1,$this->object->getMember_id());
    }

}
